name: websiteportfilio
version: 1.0.0+1
publish_to: none
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  flutter_screenutil: ^5.8.4
  firebase_core: ^2.15.0
  font_awesome_flutter: ^10.1.0
  get_storage: ^2.0.3
  http: ^1.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

